#!/usr/bin/env bash

# Reloads the bar if already running
sketchybar --remove '/.*/'

# Load the color scheme
source "$CONFIG_DIR/styles/colors.sh"

# -----------------------------------------------------
# 1. Bar Settings
# -----------------------------------------------------
sketchybar --bar height=30 \
                 color=$BAR_COLOR \
                 shadow=on \
                 position=top \
                 sticky=on \
                 padding_left=10 \
                 padding_right=30 \
                 corner_radius=0

# -----------------------------------------------------
# 2. Default Item Settings
# -----------------------------------------------------
# Using WHITE for standard text/icons and ACCENT_COLOR for highlights if desired
sketchybar --default updates=when_shown \
                     icon.font="Hack Nerd Font:Regular:16.0" \
                     label.font="Hack Nerd Font:Regular:14.0" \
                     icon.color=$WHITE \
                     label.color=$WHITE \
                     label.padding_left=8 \
                     padding_left=5 \
                     padding_right=5

# -----------------------------------------------------
# 3. 
# -----------------------------------------------------
SPACE_ICONS=("1" "2" "3" "4" "5")
for i in "${!SPACE_ICONS[@]}"
do
  sid=$(($i+1))
  sketchybar --add space space.$sid left \
             --set space.$sid space=$sid \
                              icon=${SPACE_ICONS[i]} \
                              icon.padding_left=10 \
                              icon.padding_right=10 \
                              background.color=$ITEM_BG_COLOR \
                              background.corner_radius=5 \
                              background.height=20 \
                              background.drawing=on
done

# Separator
sketchybar --add item separator left \
           --set separator icon= \
                           icon.font="Hack Nerd Font:Regular:12.0" \
                           label.drawing=off \
                           padding_left=10 \
                           padding_right=10

# Front Application
sketchybar --add item front_app left \
           --set front_app icon.drawing=off \
                           label.font="Hack Nerd Font:Bold:14.0" \
                           associated_display=active \
                           script="$CONFIG_DIR/plugins/front_app.sh" \
           --subscribe front_app front_app_switched

# -----------------------------------------------------
# 4. Right Side Items
# -----------------------------------------------------

# Time (Clock Icon)
sketchybar --add item clock right \
           --set clock update_freq=10 \
                       icon= \
                       padding_left=10 \
                       script="$CONFIG_DIR/plugins/clock.sh"

# Date (Calendar Icon)
sketchybar --add item calendar right \
           --set calendar update_freq=60 \
                          icon= \
                          padding_left=10 \
                          script="$CONFIG_DIR/plugins/calendar.sh"

# Battery
sketchybar --add item battery right \
           --set battery update_freq=120 \
                         script="$CONFIG_DIR/plugins/battery.sh" \
                         padding_left=10 \
                         padding_right=10 \
           --subscribe battery system_woke power_source_change

# CPU
sketchybar --add item cpu right \
           --set cpu  update_freq=2 \
                      icon=􀧓  \
                      script="$CONFIG_DIR/plugins/cpu.sh"           

# WIFI
sketchybar --add item net right                  \
           --set net script="$CONFIG_DIR/plugins/net.sh" \
                     update_freq=20 \
                     updates=on                  \
                     label.drawing=off           \
           --subscribe net wifi_change

# VPN
sketchybar -m --add item vpn right \
              --set vpn icon= \
                        update_freq=5 \
                        script="$CONFIG_DIR/plugins/vpn.sh"

# Volume
sketchybar -m --add item sound right \
              --set sound \
              update_freq=5 \
              icon.color=0xffd08770 \
              script="$CONFIG_DIR/plugins/sound.sh"

# -----------------------------------------------------
# 5. Finalize
# -----------------------------------------------------
# Forces all scripts to run once to populate the bar
sketchybar --update
