#!/usr/bin/env bash

# Reloads the bar if already running
sketchybar --remove '/.*/'

# Load the color scheme and padding scheme
source "$CONFIG_DIR/styles/colors.sh"
source "$CONFIG_DIR/styles/paddings.sh"
source "$CONFIG_DIR/styles/icons.sh"

# -----------------------------------------------------
# 1. Bar Settings
# -----------------------------------------------------
sketchybar --bar height=30 \
                 color=$BAR_COLOR \
                 shadow=on \
                 position=top \
                 sticky=on \
                 padding_left=$PAD_BAR_LEFT \
                 padding_right=$PAD_BAR_RIGHT \
                 corner_radius=0

# -----------------------------------------------------
# 2. Default Item Settings
# -----------------------------------------------------
# Using WHITE for standard text/icons and ACCENT_COLOR for highlights if desired
sketchybar --default updates=when_shown \
                     icon.font="Hack Nerd Font:Regular:16.0" \
                     label.font="Hack Nerd Font:Regular:14.0" \
                     icon.color=$WHITE \
                     label.color=$WHITE \
                     label.padding_left=$PAD_LABEL_LEFT \
                     padding_left=$PAD_ITEM_LEFT \
                     padding_right=$PAD_ITEM_RIGHT \
                     \
                     icon.padding_left=$PAD_ICON_LEFT \
                     label.padding_right=$PAD_LABEL_RIGHT \
                     background.drawing=on \
                     background.color=$ITEM_BG_COLOR \
                     background.corner_radius=5 \
                     background.height=24 \
                     background.border_width=1 \
                     background.border_color=$ACCENT_COLOR

# -----------------------------------------------------
# 3. Left Side Items
# -----------------------------------------------------
SPACE_ICONS=("1" "2" "3" "4" "5")
for i in "${!SPACE_ICONS[@]}"
do
  sid=$(($i+1))
  sketchybar --add space space.$sid left \
             --set space.$sid space=$sid \
                              icon=${SPACE_ICONS[i]} \
                              icon.padding_left=$PAD_SPACE_ICON_LEFT \
                              icon.padding_right=$PAD_SPACE_ICON_RIGHT \
                              background.color=$ITEM_BG_COLOR \
                              background.corner_radius=5 \
                              background.height=20 \
                              background.drawing=on
done

# Separator
sketchybar --add item separator left \
           --set separator icon=$ICON_SEPARATOR \
                           icon.font="Hack Nerd Font:Regular:12.0" \
                           label.drawing=off \
                           padding_left=$PAD_SEPARATOR_LEFT \
                           padding_right=$PAD_SEPARATOR_RIGHT \
                           icon.padding_right=$PAD_ICON_RIGHT 

# Front Application
sketchybar --add item front_app left \
           --set front_app icon.drawing=off \
                           label.font="Hack Nerd Font:Bold:14.0" \
                           associated_display=active \
                           script="$CONFIG_DIR/plugins/front_app.sh" \
           --subscribe front_app front_app_switched

# -----------------------------------------------------
# 4. Right Side Items
# -----------------------------------------------------

# Time (Clock Icon)
sketchybar --add item clock right \
           --set clock update_freq=10 \
                       icon=$ICON_CLOCK \
                       padding_left=$PAD_RIGHT_ITEM_LEFT \
                       script="$CONFIG_DIR/plugins/clock.sh" \
 

# Date (Calendar Icon)
sketchybar --add item calendar right \
           --set calendar update_freq=60 \
                          icon=$ICON_CALENDAR \
                          padding_left=$PAD_RIGHT_ITEM_LEFT \
                          script="$CONFIG_DIR/plugins/calendar.sh"

# Battery
sketchybar --add item battery right \
           --set battery update_freq=120 \
                         script="$CONFIG_DIR/plugins/battery.sh" \
                         padding_left=$PAD_RIGHT_ITEM_LEFT \
           --subscribe battery system_woke power_source_change

# CPU
sketchybar --add item cpu right \
           --set cpu  update_freq=2 \
                      icon=$ICON_CPU \
                      padding_left=$PAD_RIGHT_ITEM_LEFT \
                      script="$CONFIG_DIR/plugins/cpu.sh"

# WIFI
sketchybar --add item net right \
           --set net script="$CONFIG_DIR/plugins/net.sh" \
                     update_freq=20 \
                     padding_left=$PAD_RIGHT_ITEM_LEFT \
                     updates=on \
                     label.drawing=off \
                     icon.padding_left=6 \
                     icon.padding_right=$PAD_ICON_RIGHT \
           --subscribe net wifi_change

# VPN
sketchybar -m --add item vpn right \
              --set vpn icon=$ICON_VPN \
                        padding_left=$PAD_RIGHT_ITEM_LEFT \
                        update_freq=5 \
                        script="$CONFIG_DIR/plugins/vpn.sh"

# Volume
sketchybar -m --add item sound right \
              --set sound update_freq=5 \
                          icon.color=0xffd08770 \
                          padding_left=$PAD_RIGHT_ITEM_LEFT \
                          script="$CONFIG_DIR/plugins/sound.sh"

# Input Source / Keyboard Layout
sketchybar --add item input_source right \
           --set input_source update_freq=2 \
                              icon=$ICON_KEYBOARD \
                              padding_left=$PAD_RIGHT_ITEM_LEFT \
                              script="$CONFIG_DIR/plugins/input_source.sh" \
           --subscribe input_source mouse.clicked

# -----------------------------------------------------
# 5. Finalize
# -----------------------------------------------------
# Forces all scripts to run once to populate the bar
sketchybar --update
